---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint codebase

#############################
# Start the job on all push #
#############################
on:
  push:
  pull_request:
    branches: [main, v1]

###############
# Set the Job #
###############
jobs:
  build:
    name: Lint codebase
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint codebase
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: v1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (experiments/archive/.*|outputs/.*|jaad_pedestrian_100/.*|data/.*)
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML: true
          VALIDATE_JSON: false
